name: Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  panvimdoc:
    runs-on: ubuntu-latest
    container: pandoc/minimal:2.17-alpine

    steps:
    - uses: actions/checkout@v2
    
    - name: Install requirements
      run: |
        apk update && apk upgrade 
        apk add make bash curl coreutils neovim

    - name: Clean docs
      run: rm -v doc/tangerine.txt

    - name: Run panvimdoc
      run: make vimdoc
