name: Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  vimdoc:
    runs-on: ubuntu-latest
    container: pandoc/minimal:2.17-alpine

    steps:
    - uses: actions/checkout@v2
    
    - name: Install requirements
      run: |
        apk update && apk upgrade 
        apk add make bash curl coreutils neovim

    - name: Clean previous build
      run:  make clean

    - name: Build vimdoc
      run:  make vimdoc

    - uses: actions/upload-artifact@master
      with:
        name: vimdoc
        path: doc

  fennel:
    runs-on: ubuntu-latest
    container: alpine

    steps:
    - uses: actions/checkout@v2
    
    - name: Install requirements
      run: |
        apk update && apk upgrade 
        apk add make bash curl coreutils lua5.4
        # links lua5.4 -> lua
        cd /usr/bin && ln -s lua5.4 lua
        cd /usr/lib && ln -s lua5.4/liblua.so liblua5.4.so

    - name: Clean previous build
      run:  make clean

    - name: Copy dependencies
      run: make deps

    - name: Build fennel
      run: make fnl

    - uses: actions/upload-artifact@master
      with:
        name: fennel-out
        path: lua

  commit:
    runs-on: ubuntu-latest
    needs: [vimdoc, fennel]
    
    steps:
    - uses: actions/checkout@v2

    - name: Clean previous build
      run:  make clean

    - name: Download vimdoc
      uses: actions/download-artifact@v2
      with:
        name: vimdoc
        path: doc

    - name: Artifact fennel
      uses: actions/download-artifact@v2
      with:
        name: fennel-out
        path: lua

    - name: Checks files
      run: |
        ls -l doc
        ls -l lua

