name: Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install requirements
      run: |
        sudo apt update -y
        sudo apt install -y neovim lua5.3 pandoc

    - name: build Fennel
      run: make fnl
    
    - name: build vimdoc
      uses: docker
      with:
        image: .github/workflows/pandoc.Dockerfile
          
    - name: copy dependencies
      run: make deps
