name: Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install requirements
      run: sudo apt install -y lua5.3 pandoc

    - name: build Fennel
      run: make fnl
    
    - name: build vimdoc
      run: make vimdoc
    
    - name: copy dependencies
      run: make deps
