name: Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  vimdoc:
    runs-on: ubuntu-latest
    container: pandoc/minimal:2.17-alpine

    steps:
    - uses: actions/checkout@v2
    
    - name: Install requirements
      run: |
        apk update && apk upgrade 
        apk add make bash curl coreutils neovim

    - name: Clean docs
      run: rm -v doc/tangerine.txt

    - name: Run panvimdoc
      run: make vimdoc

    - uses: actions/upload-artifact@master
      with:
        name: vimdoc.txt
        path: doc/tangerine.txt


  commit:
    runs-on: ubuntu-latest
    needs: [vimdoc]
    
    steps:
    - uses: actions/checkout@v2

    - name: Run Clean
      run: make clean

    - run: ls -a doc

    - uses: actions/download-artifact@master
      with:
        name: vimdoc.txt
        path: doc/tangerine.txt

    - run: cat doc/tangerine.txt

