name: Build CI

on: 
  pull_request:
  push:
    paths:
      - README.md
      - Makefile
      - deps/**
      - fnl/**
      - scripts/**
      - .github/**

jobs:
  loc:
    name: lines of code
    runs-on: ubuntu-latest
    container: alpine

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Install requirements
      run: |
        apk update && apk upgrade 
        apk add make git bash curl coreutils findutils

    - name: FENNEL
      run:  make loc-fennel LOC_HEAD="HEAD"

    - name: BASH
      run:  make loc-bash LOC_HEAD="HEAD"

    - name: MARKDOWN
      run:  make loc-markdown LOC_HEAD="HEAD"

    - name: MAKEFILE
      run:  make loc-makefile LOC_HEAD="HEAD"

    - name: YAML
      run:  make loc-yaml LOC_HEAD="HEAD"

  vimdoc:
    runs-on: ubuntu-latest
    container: pandoc/minimal:2.17-alpine

    steps:
    - uses: actions/checkout@v2
    
    - name: Install requirements
      run: |
        apk update && apk upgrade 
        apk add make bash curl coreutils findutils neovim

    - name: Clean previous build
      run:  make clean

    - name: Build vimdoc
      run:  make vimdoc

    - uses: actions/upload-artifact@v2
      with:
        name: vimdoc
        path: doc

  fennel:
    runs-on: ubuntu-latest
    container: alpine

    steps:
    - uses: actions/checkout@v2
    
    - name: Install requirements
      run: |
        apk update && apk upgrade 
        apk add make bash curl coreutils findutils lua5.4
        # links lua5.4 -> lua
        cd /usr/bin && ln -s lua5.4 lua
        cd /usr/lib && ln -s lua5.4/liblua.so liblua5.4.so

    - name: Clean previous build
      run:  make clean

    - name: Copy dependencies
      run: make deps

    - name: Build fennel
      run: make fnl

    - uses: actions/upload-artifact@v2
      with:
        name: fennel-out
        path: lua

  commit:
    name: commit changes
    runs-on: ubuntu-latest
    needs: [vimdoc, fennel]
    
    steps:
    - uses: actions/checkout@v2

    - name: Clean previous build
      run:  make clean

    - name: Download vimdoc
      uses: actions/download-artifact@v2
      with:
        name: vimdoc
        path: doc

    - name: Download fennel:out
      uses: actions/download-artifact@v2
      with:
        name: fennel-out
        path: lua

    - name: Print Changes
      run:  git status --short --ignored

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: '[auto]: build deps'
        file_pattern: lua doc/tangerine.txt

